name = "TrainingBook"
uuid = "2341ea87-aabe-4153-929b-2a5b9716355c"
authors = ["Jonathan Miller jonathan.miller@fieldofnodes.com"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
